services:
  yugabyte-db:
    image: yugabytedb/yugabyte:2025.1.1.1-b1
    container_name: yugabyte-db
    ports:
      - "7001:7000"         # Master UI
      - "9001:9000"         # Tserver UI
      - '5433:5433'         # YSQL (Postgres API)
      - "9042:9042"         # YCQL (Cassandra API)
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    command: |
      bash -c "
      # Create database and user as soon as database is up
      until [ -z "POSTGRES_USER" ] || PGPASSWORD=yugabyte /home/yugabyte/bin/ysqlsh -h $(hostname) -v ON_ERROR_STOP=1 \\
       -c \"CREATE DATABASE $${POSTGRES_DB:-$${POSTGRES_USER}};\" \\
       -c \"CREATE USER $${POSTGRES_USER} WITH PASSWORD '$${POSTGRES_PASSWORD}';\" \\
       -c \"ALTER USER $${POSTGRES_USER} WITH SUPERUSER;\" \\
       -c \"ALTER USER $${POSTGRES_USER} WITH CREATEDB;\" \\
       -c \"ALTER USER $${POSTGRES_USER} WITH CREATEROLE;\" \\
       -c \"ALTER USER $${POSTGRES_USER} WITH REPLICATION;\" \\
       -c \"ALTER USER $${POSTGRES_USER} WITH BYPASSRLS;\" \\
       -c \"GRANT ALL PRIVILEGES ON DATABASE $${POSTGRES_DB:-$${POSTGRES_USER}} TO $${POSTGRES_USER};\" \\
       2>/dev/null
       do
        echo \"Retrying database and superuser creation...\" ; sleep 2
       done &
      # Now start Yugabyte-DB
      bin/yugabyted start --daemon=false"
    volumes:
      - yugabyte_data:/home/yugabyte/yb_data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: |
        bash -c '
        # Connect to custom database and run a simple query
        PGPASSWORD=$${POSTGRES_PASSWORD} /home/yugabyte/bin/ysqlsh -h $(hostname) -p 5433 -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c "
        SELECT
          current_database() as database,
          current_user as user,
          version() as version;
        " >/dev/null 2>&1 || exit 1'
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 90s
    env_file:
      - .env
# To login into YSQL: docker exec -it yugabyte-db bash -c 'PGPASSWORD=secret /home/yugabyte/bin/ysqlsh -h $(hostname) -U my_user -d my_db'
# To load schema via SQL scripts: docker exec -it yugabyte-db bash -c 'PGPASSWORD=secret /home/yugabyte/bin/ysqlsh -h $(hostname) -U my_user -d my_db -f /docker-entrypoint-initdb.d/*.sql'

  app-jre:
    image: app/postgre-app-jre:v1
    build:
      context: .
      dockerfile: jre.Dockerfile
    environment:
      DB_HOST: 'yugabyte-db'
      DB_PORT: '5433'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      OTEL_SERVICE_NAME: demo-postgre-app
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4318
      OTEL_PROFILING_ENABLED: "true"
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      JAVA_OPTS: >-
        -Xmx500m
      APP_ARGS: >-
        --spring.threads.virtual.enabled=true
        --spring.docker.compose.enabled=false
        --spring.profiles.active=yugabyte,prod
        --server.shutdown=immediate
        --management.otlp.metrics.export.enabled=true
        --management.tracing.sampling.probability=0.1
        --management.otlp.metrics.export.url=http://lgtm:4318/v1/metrics 
        --management.opentelemetry.tracing.export.otlp.endpoint=http://lgtm:4318/v1/traces
        --management.logging.export.enabled=true
        --management.opentelemetry.logging.export.otlp.endpoint=http://lgtm:4318/v1/logs
    ports:
        - "8090:8090"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 300M
    depends_on:
      yugabyte-db:
        condition: service_healthy
      lgtm:
        condition: service_started
    env_file:
      - .env

  app-native:
      image: app/postgre-app-native:v0
      build:
        context: .
        dockerfile: native.Dockerfile
      environment:
        DB_HOST: 'yugabyte-db'
        DB_PORT: '5433'
        DB_NAME: '${DB_NAME}'
        DB_USER: '${DB_USER}'
        DB_PASSWORD: '${DB_PASSWORD}'
        APP_ARGS: >-
          --spring.threads.virtual.enabled=true
          --spring.docker.compose.enabled=false
          --spring.profiles.active=yugabyte,prod
          --server.shutdown=immediate
          --management.otlp.metrics.export.enabled=true
          --management.tracing.sampling.probability=0.1
          --management.otlp.metrics.export.url=http://lgtm:4318/v1/metrics
          --management.opentelemetry.tracing.export.otlp.endpoint=http://lgtm:4318/v1/traces
          --management.logging.export.enabled=true
          --management.opentelemetry.logging.export.otlp.endpoint=http://lgtm:4318/v1/logs
      ports:
        - "8090:8090"
      deploy:
        mode: replicated
        replicas: 1
        resources:
          limits:
            cpus: '1.0'
            memory: 512M
          reservations:
            cpus: '0.5'
            memory: 300M
      depends_on:
        postgres-db:
          condition: service_healthy
        lgtm:
          condition: service_started
      env_file:
        - .env

  lgtm:
    image: grafana/otel-lgtm:0.13.0
    container_name: lgtm
    ports:
      - '3000:3000'   # Grafana UI
      - '4317:4317'   # OTLP gRPC
      - '4318:4318'   # OTLP HTTP
      - '9090:9090'   # Prometheus UI
      - '4040:4040'   # Loki Query UI
    environment:
      - 'GF_PATHS_DATA=/data/grafana'
      - 'ENABLE_LOGS_ALL=true'
    volumes:
      - lgtm_data:/data/grafana
      - lgtm_data:/data/prometheus
      - lgtm_data:/data/loki
    env_file:
      - .env

volumes:
  yugabyte_data:
  lgtm_data:
